# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  IMAGE_NAME: "docker.pkg.github.com/geometrein/finland-news/finland-news-eng"
  CONTAINER_NAME_EN: finland-news-eng

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push_to_registry:
      name: Push Docker image to GitHub Packages
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v2
        - name: Push to GitHub Packages
          uses: docker/build-push-action@v1
          with:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            registry: docker.pkg.github.com
            repository: geometrein/finland-news/finland-news-eng
            tag_with_sha: true
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: push_to_registry

    steps:
      - name: Deploy the FI version
        uses: appleboy/ssh-action@v0.1.3
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: root
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: CONTAINER_NAME_EN,IMAGE_NAME,GITHUB_SHA
          script: |
            # Stop running container
            docker stop $(echo $CONTAINER_NAME_EN)
            # Remove old container
            docker rm $(echo $CONTAINER_NAME_EN)
            # Run a new container from a new image
            docker run -d \
            --restart always \
            --network br0 \
            -v point_en:/bot/point \
            --name $(echo $CONTAINER_NAME_EN) \
            $(echo $IMAGE_NAME):sha-$(echo $GITHUB_SHA | head -c7)

      - name: Clean up docker old images
        uses: appleboy/ssh-action@v0.1.3
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: root
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Clean up old docker images
            docker rmi $(docker images -a -q) || true
            docker volume prune -f || true

